name: Deploy Static App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:  
      - 'apps/react/**'

jobs:
  build:
    name: Deploy Static App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Get pnpm store directory
        id: pnpm-store-dir-path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build:static
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync ./dist/ s3://exercise-deploy-static
          aws s3 cp s3://exercise-deploy-static/index.html s3://exercise-deploy-static/index.html --metadata-directive REPLACE --cache-control no-cache --content-type text/html

      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id EUCHD6RVACQGD --paths "/index.html" "/assets/*"
